compatibility_data = {
    "ES2020": 780,
    "ES2015": 721,
    "ES2022": 569,
    "ES5": 520,
    "ES2017": 329,
    "ES2018": 273,
    "ES2019": 122,
    "ES2021": 56,
    "ES2016": 26,
}


transparency_data = {
    "JEST": {
        "all": 3349,
        "accessible": 3349,
        "syntacticallyCompatible": 502,
        "compatible": 133,
        "eventuallyCompatible": 279,
        "unknownCompatible": 0,
        "unknownEventuallyCompatible": 0,
        "transpilationOK": 2158,
        "transpilationKO": 598,
        "originalSomeSuccessSomeFailure": 0,
        "toolSomeSuccessSomeFailure": 0,
        "compatibilityIssues": {
            "CrashError": 97,
            "BabelError": 598,
            "ParseError": 1797,
            "AnalysisError": 380,
        },
        "transparencyAnalyzable": 278,
        "nonTransparent": 225,
        "transparent": 53,
        "uncaughtErrorTypes": {
            "ReferenceError": 2,
            "SyntaxError": 25,
            "TypeError": 54,
            "OtherError": 144,
        },
    },
    "IF-Transpiler": {
        "all": 3349,
        "accessible": 3349,
        "syntacticallyCompatible": 502,
        "compatible": 82,
        "eventuallyCompatible": 205,
        "unknownCompatible": 0,
        "unknownEventuallyCompatible": 0,
        "transpilationOK": 2446,
        "transpilationKO": 362,
        "originalSomeSuccessSomeFailure": 0,
        "toolSomeSuccessSomeFailure": 0,
        "compatibilityIssues": {
            "CrashError": 48,
            "BabelError": 361,
            "ParseError": 46,
            "AnalysisError": 2689,
        },
        "transparencyAnalyzable": 205,
        "nonTransparent": 177,
        "transparent": 28,
        "uncaughtErrorTypes": {
            "ReferenceError": 1,
            "SyntaxError": 42,
            "TypeError": 102,
            "OtherError": 35,
        },
    },
    "GIFC": {
        "all": 3349,
        "accessible": 3349,
        "syntacticallyCompatible": 1835,
        "compatible": 835,
        "eventuallyCompatible": 1370,
        "unknownCompatible": 0,
        "unknownEventuallyCompatible": 2,
        "transpilationOK": 1243,
        "transpilationKO": 218,
        "originalSomeSuccessSomeFailure": 0,
        "toolSomeSuccessSomeFailure": 1,
        "compatibilityIssues": {
            "CrashError": 81,
            "BabelError": 218,
            "ParseError": 56,
            "AnalysisError": 1622,
        },
        "transparencyAnalyzable": 1367,
        "nonTransparent": 1307,
        "transparent": 60,
        "uncaughtErrorTypes": {
            "ReferenceError": 585,
            "SyntaxError": 348,
            "TypeError": 1291,
            "OtherError": 331,
        },
    },
    "Jalangi": {
        "all": 3349,
        "accessible": 3349,
        "syntacticallyCompatible": 502,
        "compatible": 490,
        "eventuallyCompatible": 2825,
        "unknownCompatible": 0,
        "unknownEventuallyCompatible": 50,
        "transpilationOK": 2411,
        "transpilationKO": 318,
        "originalSomeSuccessSomeFailure": 3,
        "toolSomeSuccessSomeFailure": 8,
        "compatibilityIssues": {
            "CrashError": 127,
            "BabelError": 318,
            "ParseError": 28,
            "AnalysisError": 1,
        },
        "transparencyAnalyzable": 2812,
        "nonTransparent": 912,
        "transparent": 1900,
        "uncaughtErrorTypes": {
            "ReferenceError": 240,
            "SyntaxError": 240,
            "TypeError": 547,
            "OtherError": 146,
        },
    },
    "Linvail": {
        "all": 3349,
        "accessible": 3349,
        "syntacticallyCompatible": 1835,
        "compatible": 361,
        "eventuallyCompatible": 471,
        "unknownCompatible": 0,
        "unknownEventuallyCompatible": 1,
        "transpilationOK": 335,
        "transpilationKO": 89,
        "originalSomeSuccessSomeFailure": 0,
        "toolSomeSuccessSomeFailure": 9,
        "compatibilityIssues": {
            "CrashError": 1800,
            "BabelError": 89,
            "ParseError": 44,
            "AnalysisError": 944,
        },
        "transparencyAnalyzable": 462,
        "nonTransparent": 241,
        "transparent": 221,
        "uncaughtErrorTypes": {
            "ReferenceError": 100,
            "SyntaxError": 108,
            "TypeError": 171,
            "OtherError": 80,
        },
    },
    "Project Foxhound": {
        "all": 3349,
        "accessible": 3349,
        "syntacticallyCompatible": 3349,
        "compatible": 3079,
        "eventuallyCompatible": 3079,
        "unknownCompatible": 1,
        "unknownEventuallyCompatible": 1,
        "transpilationOK": 0,
        "transpilationKO": 0,
        "originalSomeSuccessSomeFailure": 5,
        "toolSomeSuccessSomeFailure": 36,
        "compatibilityIssues": {
            "CrashError": 269,
            "BabelError": 0,
            "ParseError": 0,
            "AnalysisError": 0,
        },
        "transparencyAnalyzable": 3035,
        "nonTransparent": 78,
        "transparent": 2957,
        "uncaughtErrorTypes": {
            "ReferenceError": 1,
            "SyntaxError": 1,
            "TypeError": 67,
            "OtherError": 10,
        },
    },
}
