global_data = {
    "JEST": {
        "all": 5000,
        "accessible": 3410,
        "syntacticallyCompatible": 538,
        "compatible": 141,
        "eventuallyCompatible": 278,
        "unknownCompatibility": 0,
        "transpilationOK": 2462,
        "transpilationKO": 234,
        "originalSomeSuccessSomeFailure": 5,
        "toolSomeSuccessSomeFailure": 0,
        "compatibilityIssues": {
            "CrashError": 182,
            "BabelError": 234,
            "ParseError": 1881,
            "AnalysisError": 835,
        },
        "transparencyAnalyzable": 267,
        "noneTraceExists": 0,
        "originalTraceExists": 0,
        "toolTraceExists": 0,
        "bothTraceExists": 267,
        "nonTransparent": 221,
        "transparent": 46,
        "uncaughtErrorTypes": {
            "ReferenceError": 2,
            "SyntaxError": 25,
            "TypeError": 54,
            "OtherError": 140,
        },
    },
    "IF-Transpiler": {
        "all": 5000,
        "accessible": 3410,
        "syntacticallyCompatible": 538,
        "compatible": 81,
        "eventuallyCompatible": 197,
        "unknownCompatibility": 0,
        "transpilationOK": 2342,
        "transpilationKO": 197,
        "originalSomeSuccessSomeFailure": 4,
        "toolSomeSuccessSomeFailure": 2,
        "compatibilityIssues": {
            "CrashError": 344,
            "BabelError": 197,
            "ParseError": 209,
            "AnalysisError": 2463,
        },
        "transparencyAnalyzable": 187,
        "noneTraceExists": 0,
        "originalTraceExists": 0,
        "toolTraceExists": 0,
        "bothTraceExists": 187,
        "nonTransparent": 165,
        "transparent": 22,
        "uncaughtErrorTypes": {
            "ReferenceError": 2,
            "SyntaxError": 33,
            "TypeError": 99,
            "OtherError": 35,
        },
    },
    "GIFC": {
        "all": 5000,
        "accessible": 3410,
        "syntacticallyCompatible": 1941,
        "compatible": 878,
        "eventuallyCompatible": 1379,
        "unknownCompatibility": 26,
        "transpilationOK": 1162,
        "transpilationKO": 193,
        "originalSomeSuccessSomeFailure": 9,
        "toolSomeSuccessSomeFailure": 115,
        "compatibilityIssues": {
            "CrashError": 153,
            "BabelError": 193,
            "ParseError": 53,
            "AnalysisError": 1606,
        },
        "transparencyAnalyzable": 1247,
        "noneTraceExists": 0,
        "originalTraceExists": 99,
        "toolTraceExists": 0,
        "bothTraceExists": 1148,
        "nonTransparent": 1096,
        "transparent": 52,
        "uncaughtErrorTypes": {
            "ReferenceError": 462,
            "SyntaxError": 266,
            "TypeError": 1082,
            "OtherError": 190,
        },
    },
    "Jalangi": {
        "all": 5000,
        "accessible": 3410,
        "syntacticallyCompatible": 538,
        "compatible": 462,
        "eventuallyCompatible": 1817,
        "unknownCompatibility": 629,
        "transpilationOK": 2076,
        "transpilationKO": 243,
        "originalSomeSuccessSomeFailure": 15,
        "toolSomeSuccessSomeFailure": 763,
        "compatibilityIssues": {
            "CrashError": 580,
            "BabelError": 243,
            "ParseError": 141,
            "AnalysisError": 0,
        },
        "transparencyAnalyzable": 1037,
        "noneTraceExists": 0,
        "originalTraceExists": 3,
        "toolTraceExists": 1,
        "bothTraceExists": 1033,
        "nonTransparent": 189,
        "transparent": 844,
        "uncaughtErrorTypes": {
            "ReferenceError": 6,
            "SyntaxError": 39,
            "TypeError": 115,
            "OtherError": 48,
        },
    },
    "Linvail": {
        "all": 5000,
        "accessible": 3410,
        "syntacticallyCompatible": 1941,
        "compatible": 430,
        "eventuallyCompatible": 560,
        "unknownCompatibility": 21,
        "transpilationOK": 408,
        "transpilationKO": 108,
        "originalSomeSuccessSomeFailure": 4,
        "toolSomeSuccessSomeFailure": 53,
        "compatibilityIssues": {
            "CrashError": 1616,
            "BabelError": 108,
            "ParseError": 45,
            "AnalysisError": 1060,
        },
        "transparencyAnalyzable": 498,
        "noneTraceExists": 0,
        "originalTraceExists": 62,
        "toolTraceExists": 0,
        "bothTraceExists": 436,
        "nonTransparent": 221,
        "transparent": 215,
        "uncaughtErrorTypes": {
            "ReferenceError": 66,
            "SyntaxError": 90,
            "TypeError": 172,
            "OtherError": 47,
        },
    },
    "Project Foxhound": {
        "all": 5000,
        "accessible": 3410,
        "syntacticallyCompatible": 3410,
        "compatible": 2990,
        "eventuallyCompatible": 2990,
        "unknownCompatibility": 12,
        "transpilationOK": 0,
        "transpilationKO": 0,
        "originalSomeSuccessSomeFailure": 25,
        "toolSomeSuccessSomeFailure": 79,
        "compatibilityIssues": {
            "CrashError": 408,
            "BabelError": 0,
            "ParseError": 0,
            "AnalysisError": 0,
        },
        "transparencyAnalyzable": 2880,
        "noneTraceExists": 2,
        "originalTraceExists": 4,
        "toolTraceExists": 2,
        "bothTraceExists": 2872,
        "nonTransparent": 65,
        "transparent": 2807,
        "uncaughtErrorTypes": {
            "ReferenceError": 5,
            "SyntaxError": 1,
            "TypeError": 55,
            "OtherError": 9,
        },
    },
}
